# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(default=0)),
                ('corte', models.CharField(blank=True, max_length=255, null=True)),
                ('exp', models.CharField(blank=True, max_length=100, null=True)),
                ('autos', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('sobre', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=9999999, null=True)),
                ('actora', models.CharField(blank=True, max_length=255, null=True)),
                ('demandada', models.CharField(blank=True, max_length=255, null=True)),
                ('jueces', models.CharField(blank=True, max_length=255, null=True)),
                ('leyes', models.CharField(blank=True, max_length=255, null=True)),
                ('citados', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('resultados', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('fallos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallos.Fallos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(default='e85c8905-e', max_length=11, unique=True)),
                ('autos', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=9999999, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MySearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
