# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fallos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField(default=0)),
                ('tomo', models.CharField(blank=True, max_length=100, null=True)),
                ('autos', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=9999, null=True)),
                ('actora', models.CharField(blank=True, max_length=150, null=True)),
                ('demandada', models.CharField(blank=True, max_length=150, null=True)),
                ('deducido', models.CharField(blank=True, max_length=150, null=True)),
                ('mayoria', models.CharField(blank=True, max_length=150, null=True)),
                ('disidencia', models.CharField(blank=True, max_length=150, null=True)),
                ('resultado', models.CharField(blank=True, max_length=150, null=True)),
                ('origen', models.CharField(blank=True, max_length=150, null=True)),
                ('anterior', models.CharField(blank=True, max_length=150, null=True)),
                ('legislacion', models.CharField(blank=True, max_length=150, null=True)),
                ('voces', models.CharField(blank=True, max_length=500, null=True)),
                ('materia', models.CharField(blank=True, max_length=500, null=True)),
                ('date_image', models.ImageField(default='NA', upload_to='media')),
                ('singnature_image', models.ImageField(default='NA', upload_to='media')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
