# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallos',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
