# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='9ad64458-5', max_length=11, unique=True),
        ),
    ]
