# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-25 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0002_fallos_corte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fallos',
            name='deducido',
        ),
    ]
