# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0002_mynotes_mysearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='compania',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='07259e5e-6', max_length=11, unique=True),
        ),
    ]
