# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0003_remove_fallos_deducido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallos',
            name='text',
            field=models.TextField(blank=True, max_length=99999, null=True),
        ),
    ]
