# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textprocessor', '0003_auto_20161217_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.TextField(blank=True, max_length=5000, null=True)),
                ('busquedas', models.TextField(blank=True, max_length=1000, null=True)),
                ('notas', models.TextField(blank=True, max_length=999999, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='fallos',
            name='text',
            field=models.TextField(blank=True, max_length=9999999, null=True),
        ),
    ]
