# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textprocessor', '0003_auto_20170210_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('fallos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textprocessor.Fallos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(default='2397bce8-f', max_length=11, unique=True)),
                ('autos', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=9999999, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
