# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0003_auto_20170123_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='db31c478-b', max_length=11, unique=True),
        ),
    ]
