# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0004_auto_20170109_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='busquedas',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notas',
        ),
    ]
