# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-26 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0004_auto_20160925_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fallos',
            old_name='singnature_image',
            new_name='signature_image',
        ),
    ]
