# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0004_auto_20170123_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mysearches',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyNotes',
        ),
        migrations.DeleteModel(
            name='MySearches',
        ),
    ]
