# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0005_auto_20170210_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='488f46eb-c', max_length=11, unique=True),
        ),
    ]
