# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0005_auto_20170109_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.TextField(blank=True, max_length=9999999, null=True)),
            ],
        ),
    ]
