# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0005_auto_20160926_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallos',
            name='text',
            field=models.TextField(blank=True, max_length=999999, null=True),
        ),
    ]
