# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0006_auto_20160929_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallos',
            name='materia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fallos',
            name='voces',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
