# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0006_mynotes_mysearches'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysearches',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='9c55fafb-6', max_length=11, unique=True),
        ),
    ]
