# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0007_auto_20170124_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='087c40fd-3', max_length=11, unique=True),
        ),
    ]
