# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0007_auto_20161011_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fallos',
            old_name='tipo',
            new_name='sobre',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='anterior',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='date_image',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='legislacion',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='signature_image',
        ),
    ]
