# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0008_auto_20161017_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fallos',
            old_name='tomo',
            new_name='exp',
        ),
    ]
