# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0008_favorites_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='fav_url',
            new_name='fav_slug',
        ),
    ]
