# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0009_auto_20161017_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fallos',
            old_name='disidencia',
            new_name='jueces',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='mayoria',
        ),
        migrations.RemoveField(
            model_name='fallos',
            name='resultado',
        ),
    ]
