# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0009_auto_20170213_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='db6b3ce1-c', max_length=11, unique=True),
        ),
    ]
