# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0009_auto_20170110_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
