# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0010_auto_20161018_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallos',
            name='materia',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
