# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0010_auto_20170213_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallos',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='7a392747-7', max_length=11, unique=True),
        ),
    ]
