# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textprocessor', '0010_auto_20170110_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallos',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
