# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0011_auto_20170213_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fallos',
            options={},
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='40df5a28-f', max_length=11, unique=True),
        ),
    ]
