# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0011_fallos_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autos', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=9999999, null=True)),
            ],
        ),
    ]
