# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0011_auto_20161020_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallos',
            name='leyes',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='fallos',
            name='lugar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fallos',
            name='relacionados',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
