# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0012_myfavs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFavs',
            new_name='MyNotes',
        ),
    ]
