# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textprocessor', '0013_auto_20170113_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mynotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
