# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0014_paneles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneles',
            name='panel',
            field=models.TextField(max_length=9999),
        ),
    ]
