# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0014_mynotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mynotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
