# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0015_auto_20170113_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySearches',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='textprocessor.userProfile')),
                ('search', models.TextField(blank=True, null=True)),
            ],
            bases=('textprocessor.userprofile',),
        ),
    ]
