# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-14 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0015_auto_20161114_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paneles',
            name='user',
        ),
        migrations.DeleteModel(
            name='paneles',
        ),
    ]
