# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0016_mysearches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mynotes',
            name='user',
        ),
        migrations.AddField(
            model_name='mynotes',
            name='userprofile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='textprocessor.userProfile'),
            preserve_default=False,
        ),
    ]
