# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-28 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0016_auto_20161114_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallos',
            name='provincia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
