# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-06 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0017_fallos_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallos',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 6, 22, 40, 34, 890243)),
            preserve_default=False,
        ),
    ]
