# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0018_auto_20170113_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallos',
            name='resultados',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
