# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0018_auto_20170213_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallos',
            name='nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='05b93c5e-a', max_length=11, unique=True),
        ),
    ]
