# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0020_auto_20170213_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='059befc2-3', max_length=11, unique=True),
        ),
    ]
