# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0021_mynotes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotes',
            name='slug',
        ),
    ]
