# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0022_remove_mynotes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
