# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0023_mynotes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='bff36493-d', max_length=11, unique=True),
        ),
    ]
