# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textprocessor', '0024_mynotes_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotes',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='note_id',
            field=models.CharField(default='b5b8e597-2', max_length=11, unique=True),
        ),
    ]
